= {lab_name}

== ABOUT THIS LAB
In this lab we'll address some ways that can help you with some major challenges we've witnessed with some of our largest customers:

* In order to meet your customer's needs, you need the ability to deliver new capabilities through secure software applications rapidly, and continuously.
* Many customers have applications that are architected and developed in such a way that they are not easily evolvable, agile enough to meet a rapid change in business requirements, or even in a position to efficiently develop and maintain new applications, especially without reaching the same challenges again.
* IT organizations need to facilitate securely buildable and deployable applications at scale for their developers, wherever it makes sense for the business - whether on-premises, in a cloud, or even in a hybrid combination. 

== LAB ACCESS

We will be using Red Hat OpenShift as the development platform, as well as Gitea as the code repository and finally Red Hat OpenShift Dev Spaces as development environment.

[%hardbreaks]
OpenShift console URL: 
`{console_url}`
Gitea console URL: `{gitea_console_url}`
Gitea user: `{user}`
Gitea password: `{gitea_password}`
OpenShift login command: 
oc login -u `{user}` -p `{password}` `{openshift_api_url}`
Dev Spaces URL: `{devspaces_url}`
